# Generated by Django 2.2.7 on 2019-11-26 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FlightModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_type', models.CharField(max_length=20)),
                ('from_state', models.CharField(max_length=20)),
                ('from_city', models.CharField(max_length=100)),
                ('depart_date', models.DateField()),
                ('to_state', models.CharField(max_length=20)),
                ('to_city', models.CharField(max_length=100)),
                ('return_date', models.DateField(null=True)),
            ],
        ),
    ]
