# Generated by Django 2.2.7 on 2019-11-27 00:37

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flightmodel',
            name='return_date',
        ),
        migrations.AddField(
            model_name='flightmodel',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='flightmodel',
            name='seats',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='flightmodel',
            name='depart_date',
            field=models.DateTimeField(),
        ),
    ]
